/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "../../src/mmi/web/**/*.py",
    "../../src/mmi/search/**/*.py",
    "./content-stub.html",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffdcbd",
        "secondary-container": "#fc9912",
        "on-background": "#1a1c1c",
        "tertiary-fixed": "#e1e2e6",
        outline: "#747782",
        "on-surface": "#1a1c1c",
        "on-primary-fixed": "#001946",
        "error-container": "#ffdad6",
        secondary: "#8a5100",
        "on-primary-container": "#92b1ff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c5c6ca",
        tertiary: "#2c2f32",
        "surface-variant": "#e2e2e2",
        "on-tertiary-container": "#b1b2b6",
        "on-secondary-container": "#643900",
        "surface-bright": "#f9f9f9",
        "primary-fixed-dim": "#b1c5ff",
        "on-error": "#ffffff",
        "primary-container": "#1a418c",
        surface: "#f9f9f9",
        "inverse-primary": "#b1c5ff",
        "primary-fixed": "#dae2ff",
        primary: "#002a6d",
        "tertiary-container": "#434548",
        background: "#f9f9f9",
        "surface-container": "#eeeeee",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-fixed": "#2c1600",
        "inverse-surface": "#2f3131",
        "surface-tint": "#395ba8",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "on-surface-variant": "#434651",
        "inverse-on-surface": "#f0f1f1",
        "surface-dim": "#dadada",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-md": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        base: "4px",
        "stack-sm": "8px",
        gutter: "24px",
        "stack-lg": "32px",
      },
      fontFamily: {
        sans: ["Montserrat", "system-ui", "sans-serif"],
        "data-tabular": ["Montserrat", "ui-monospace", "monospace"],
      },
      fontSize: {
        "headline-md": ["1.25rem", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["1.0625rem", { lineHeight: "1.5" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5" }],
        "label-sm": ["0.75rem", { lineHeight: "1.35", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
